apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: etl-deployer
  name: etl-deployer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: etl-deployer
    spec:
      containers:
      - image: enyachoke/deployer
        imagePullPolicy: Always
        name: etl-deployer
        ports:
        - containerPort: 3000    
        resources: {}
      restartPolicy: Always
status: {}
